export const predictionQuestions_1 = [
  {
    paramLabel: "Enter age",
    headerLabel: "Enter your age",
    type: "number",
  },
  {
    paramLabel: "Enter name",
    headerLabel: "Enter your name",
    type: "text",
  },
  {
    paramLabel: "Area of Interest",
    headerLabel: "Choose Your Area Of Interest",
    type: "select",
    options: [
      { value: 2, label: "Aerospace" },
      { value: 9, label: "Architect" },
      { value: 23, label: "Animals" },
      { value: 6, label: "Auto cad" },
      { value: 24, label: "Bio chemical" },
      { value: 27, label: "Business" },
      { value: 29, label: "Business Administration" },
      { value: 15, label: "Business and law" },
      { value: 16, label: "Cloud computing" },
      { value: 13, label: "Computer" },
      { value: 31, label: "Corporate laws" },
      { value: 17, label: "Cyber Security" },
      { value: 0, label: "DataScientist" },
      { value: 21, label: "Dental" },
      { value: 28, label: "Economics" },
      { value: 8, label: "Electronics" },
      { value: 1, label: "Entrepreneur" },
      { value: 26, label: "Finance" },
      { value: 22, label: "Homeopathic Medicine" },
      { value: 7, label: "IOT" },
      { value: 4, label: "Manufacture goods" },
      { value: 18, label: "Medicine" },
      { value: 20, label: "Nursing" },
      { value: 19, label: "Physiotherapy" },
      { value: 5, label: "Production" },
      { value: 3, label: "Sound" },
      { value: 10, label: "Structural Engineer" },
      { value: 25, label: "Surgery" },
      { value: 14, label: "Technology" },
      { value: 12, label: "Transporatation" },
      { value: 11, label: "Water management" },
    ],
  },
  {
    paramLabel: "Your Education Background",
    headerLabel: "What is your Education Background?",
    type: "text",
  },
  {
    paramLabel: "Your skills",
    headerLabel: "What is your skillset?",
    type: "text",
  },
  {
    paramLabel: "Your certifications",
    headerLabel: "What certifications have you completed?",
    type: "select",
    options: [
      { label: "Shell programming", value: "shell programming" },
      { label: "Machine learning", value: "machine learning" },
      { label: "App development", value: "app development" },
      { label: "Python", value: "python" },
      { label: "R programming", value: "r programming" },
      { label: "Information security", value: "information security" },
      { label: "Hadoop", value: "hadoop" },
      { label: "Distro making", value: "distro making" },
      { label: "Full stack", value: "full stack" },
    ],
  },
  {
    paramLabel: "Your work experience",
    headerLabel: "Enter your past work experience",
    type: "textarea",
  },
];
export const predictionQuestions_2 = [
  {
    paramLabel: "Interested subjects",
    headerLabel: "Which subjects interests you the most?",
    type: "select",
    options: [
      { label: "Cloud computing", value: "cloud computing" },
      { label: "Networks", value: "networks" },
      { label: "Computer architecture", value: "Computer Architecture" },
      { label: "Programming", value: "programming" },
      { label: "Parallel computing", value: "parallel computing" },
      { label: "IOT", value: "IOT" },
      { label: "Data engineering", value: "data engineering" },
      { label: "Software engineering", value: "Software Engineering" },
      { label: "Management", value: "Management" },
      { label: "Information security", value: "information security" },
    ],
  },
  {
    paramLabel: "Acedamic percentage in Operating Systems ",
    headerLabel: "Percentage of marks obtained in Operating systems?",
    type: "number",
  },
  {
    paramLabel: "Percentage in Algorithms",
    headerLabel: "Percentage of marks obtained in Analysis of algorithms?",
    type: "number",
  },
  {
    paramLabel: "Percentage in Programming Concepts",
    headerLabel: "Percentage of marks obtained in Programming concepts?",
    type: "number",
  },
  {
    paramLabel: "Percentage in Software Engineering",
    headerLabel: "Percentage of marks obtained in Software Engineering?",
    type: "number",
  },
  {
    paramLabel: "Percentage in Computer Networks",
    headerLabel: "Percentage of marks obtained in Computer Networks?",
    type: "number",
  },
  {
    paramLabel: "Percentage in Electronics Subjects",
    headerLabel: "Percentage of marks obtained in Electronic Subjects?",
    type: "number",
  },
  {
    paramLabel: "Percentage in Computer Architecture",
    headerLabel: "Percentage of marks obtained in Computer Architecture?",
    type: "number",
  },
  {
    paramLabel: "Percentage in Mathematics",
    headerLabel: "Percentage of marks obtained in Mathematics?",
    type: "number",
  },
  {
    paramLabel: "Percentage in Communication skills",
    headerLabel: "Percentage of marks obtained in Communication skills?",
    type: "number",
  },
  {
    paramLabel: "Hours working per day",
    headerLabel: "How long do you prefer to work? (hours)",
    type: "number",
  },
  {
    paramLabel: "hackathons",
    headerLabel: "How many hackathons have you attended?",
    type: "number",
  },
  {
    paramLabel: "coding skills rating",
    headerLabel: "How would you rate your coding skills?",
    type: "range",
    max: 10,
  },
  {
    paramLabel: "public speaking points",
    headerLabel: "How would you rate your public speaking skills?",
    type: "range",
    max: 10,
  },
  {
    paramLabel: "can work long time before system? ",
    headerLabel:
      "Do you prefer working in a software environment for long hours?",
    type: "radio",
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
  },
  {
    paramLabel: "self-learning capability?",
    headerLabel: "Do you think you have self learning capability?",
    type: "radio",
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
  },
  {
    paramLabel: "Extra-courses did certifications",
    headerLabel: "Have you taken up any courses apart from academic subjects?",
    type: "radio",
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
  },
  {
    paramLabel: "certifications",
    headerLabel: "What certifications have you completed?",
    type: "select",
    options: [
      { label: "Shell programming", value: "shell programming" },
      { label: "Machine learning", value: "machine learning" },
      { label: "App development", value: "app development" },
      { label: "Python", value: "python" },
      { label: "R programming", value: "r programming" },
      { label: "Information security", value: "information security" },
      { label: "Hadoop", value: "hadoop" },
      { label: "Distro making", value: "distro making" },
      { label: "Full stack", value: "full stack" },
    ],
  },
  {
    paramLabel: "workshops",
    headerLabel: "What workshops have you attended?",
    type: "select",
    options: [
      { label: "Cloud computing", value: "cloud computing" },
      { label: "Database security", value: "database security" },
      { label: "Web technologies", value: "web technologies" },
      { label: "Data science", value: "data science" },
      { label: "Testing", value: "testing" },
      { label: "Hacking", value: "hacking" },
      { label: "Game development", value: "game development" },
      { label: "System designing", value: "system designing" },
    ],
  },
  {
    paramLabel: "talent tests taken?",
    headerLabel: "Have you taken up any talent tests?",
    type: "radio",
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
  },
  {
    paramLabel: "olympiads",
    headerLabel: "Have you attended any olympiads?",
    type: "radio",
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
  },
  {
    paramLabel: "reading and writing skills",
    headerLabel: "How would you rate your reading and writing skills?",
    type: "radio",
    options: [
      { label: "Poor", value: "poor" },
      { label: "Medium", value: "medium" },
      { label: "Excellent", value: "excellent" },
    ],
  },
  {
    paramLabel: "memory capability score",
    headerLabel: "How would you rate your memory power?",
    type: "radio",
    options: [
      { label: "Poor", value: "poor" },
      { label: "Medium", value: "medium" },
      { label: "Excellent", value: "excellent" },
    ],
  },

  {
    paramLabel: "Introvert",
    headerLabel: "Are you an introvert?",
    type: "radio",
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
  },
  {
    paramLabel: "Job/Higher Studies?",
    headerLabel: "Are you interested in working or doing higher studies?",
    type: "radio",
    options: [
      { label: "Higher Studies", value: "higherstudies" },
      { label: "Working", value: "job" },
    ],
  },
  {
    paramLabel: "Type of company want to settle in?",
    headerLabel: "What type of company do you prefer to work in?",
    type: "select",
    options: [
      { label: "Web Services", value: "Web Services" },
      { label: "SAaS services", value: "SAaS services" },
      { label: "Sales and Marketing", value: "Sales and Marketing" },
      {
        label: "Testing and Maintainance Services",
        value: "Testing and Maintainance Services",
      },
      { label: "Product development", value: "product development" },
      { label: "BPA", value: "BPA" },
      { label: "Service Based", value: "Service Based" },
      { label: "Product based", value: "Product based" },
      { label: "Finance", value: "Finance" },
      { label: "Cloud Services", value: "Cloud Services" },
    ],
  },
  {
    paramLabel: "Taken inputs from seniors or elders",
    headerLabel: "Have you sought any guidance from seniors?",
    type: "radio",
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
  },
  {
    paramLabel: "Management or Technical",
    headerLabel: "Do you prefer working in Management or Technical fields?",
    type: "radio",
    options: [
      { label: "Technical", value: "Technical" },
      { label: "management", value: "management" },
    ],
  },

  {
    paramLabel: "worked in teams ever?",
    headerLabel: "Do you have any prior experience of working in teams?",
    type: "radio",
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
  },
];
