const array = [
  "Acedamic percentage in Operating Systems",
  "percentage in Algorithms",
  "Percentage in Programming Concepts",
  "Percentage in Software Engineering",
  "Percentage in Computer Networks",
  "Percentage in Electronics Subjects",
  "Percentage in Computer Architecture",
  "Percentage in Mathematics",
  "Percentage in Communication skills",
  "Hours working per day",
  "Logical quotient rating",
  "hackathons",
  "coding skills rating",
  "public speaking points",
  "can work long time before system?",
  "self-learning capability?",
  "Extra-courses did",
  "certifications",
  "workshops",
  "talenttests taken?",
  "olympiads",
  "reading and writing skills",
  "memory capability score",
  "Interested subjects",
  "Introvert",
  "Job/Higher Studies?",
  "Type of company want to settle in?",
  "Taken inputs from seniors or elders",
  "interested in games",
  "Interested Type of Books",
  "In a Realtionship?",
  "Gentle or Tuff behaviour?",
  "Management or Technical",
  "Salary/work",
  "hard/smart worker",
  "worked in teams ever?",
  "Suggested Job Role",
];
const q = [
  "Acedamic percentage in Operating Systems ",
  "Percentage in Algorithms",
  "Percentage in Programming Concepts",
  "Percentage in Software Engineering",
  "Percentage in Computer Networks",
  "Percentage in Electronics Subjects",
  "Percentage in Computer Architecture",
  "Percentage in Mathematics",
  "Percentage in Communication skills",
  "Hours working per day",
  "hackathons",
  "coding skills rating",
  "public speaking points",
  "can work long time before system? ",
  "self-learning capability?",
  "Extra-courses did certifications",
  "certifications",
  "workshops",
  "talenttests taken?",
  "olympiads",
  "reading and writing skills",
  "memory capability score",
  "Interested subjects",
  "Introvert",
  "Job/Higher Studies?",
  "Type of company want to settle in?",
  "Taken inputs from seniors or elders",
  "interested in games",
  "Interested Type of Books",
  "In a Relationship?",
  "Gentle or Tuff behaviour",
  "Management or Technical",
  "hard/smart worker",
  "worked in teams ever?",
];
console.log(array.length);
console.log(q.length);
array.forEach((item) => {
  if (!q.includes(item)) {
    console.log(item);
  }
});
